import type { NextPage } from 'next';
import Head from 'next/head';
import MainLayout from '../layouts/MainLayout';
import { ThemeProvider } from 'styled-components';
import theme from '../styles/theme';
import { DataType, getData } from '../api/example.api';

interface IHome {
  data: DataType;
}
const Home: NextPage<IHome> = ({ data }) => {
  return (
    <ThemeProvider theme={theme}>
      <MainLayout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div>Something</div>
      </MainLayout>
    </ThemeProvider>
  );
};

export async function getStaticProps() {
  const { data } = await getData();

  return {
    data,
  };
}

export default Home;
